version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.back
    ports:
      - "5000:5000"
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.front
    ports:
      - "8883:80"
    depends_on:
      - backend
    restart: always
